### ISSUE TITLE
Display only stable Starcounter app store by default

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#10]
For Starcounter Playground, we want to cater a list of stable apps. Only the following apps will be available in the stable app store from day 1: Launcher, AppStoreClient, Images, Products, Procurement, Barcodes, People

The above apps should be uploaded to "Starcounter" app store, which is currently empty.

AppStoreClient should display only apps from "Starcounter" app store, unless configured differently.

There will be a REST-style configuration, allowing to enable or disable displaying apps from other app stores, using the app store name or `all` keyword.

Administrator should keep showing apps from all app stores.

**Comment by miyconst** [comment]
Done.

Now only *Starcounter* store is shown by default. I have uploaded Launcher to Starcounter store to see at least an item.

Configuration GET requests:

Display all stores:
```
http://localhost:8080/appstoreclient/setdisplaystores/all
```

Display only polyjuice store:
```
http://localhost:8080/appstoreclient/setdisplaystores/polyjuice
```

Display polyjuice and smörgåsbord store:
```
http://localhost:8080/appstoreclient/setdisplaystores/polyjuice,smörgåsbord
```

Revert to default settings:
```
http://localhost:8080/appstoreclient/setdisplaystores/
```
