### ISSUE TITLE
Disable uninstalling of certain apps

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#11]
For Playground project, we need to disable uninstalling of the apps that are essential for the playground:

- Launcher
- AppStoreClient
- PlaygroundWelcome

I think that the correct way is to disable uninstalling apps that are marked as "Auto-Start" in the Administrator.

**Comment by miyconst** [comment]
`Starcounter.Administrator` needs to expose this value.

Should be added to https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter.Administrator/Server/Model/AppStoreApplicationJson.json as `IsAutoStart: true/false`.

Probably @andwah can do this on Monday.

**Comment by warpech** [comment]
Just discussed with @andwah. He will consider the best solution (using autostart or create a new boolean setting to disable uninstalling of an app in AppStoreClient) and do the backend part in Administrator.

@andwah, when you're done with the Administrator, please reassign it to @miyconst so he can do the client part. We need this tomorrow.

**Comment by andwah** [comment]
Each application that is auto-started is stored in a json file. (Application that is not auto-started is not in that file). 
So i'm thinking that this is not the right place to keep the "CanBeUninstalled" flag.
Instead i suggest we store it in the application configuration file. Each "deployed" application has it's own configuration file that contains the name, description, version etc..)

**Comment by miyconst** [comment]
That does not fair, what if we want to configure different persistent apps for different databases?

**Comment by miyconst** [comment]
I just have discovered, that this already done.

We show only Starcounter store for the playgrounds, and the store does not contain Launcher, Welcome, AppStore, so the users won't be able to un-install any of those applications!

**Comment by warpech** [comment]
> That does not fair, what if we want to configure different persistent apps for different databases?

AFAIK, the app configuration file is stored separately for every database.

> We show only Starcounter store for the playgrounds, and the store does not contain Launcher, Welcome, AppStore, so the users won't be able to un-install any of those applications!

Clever! This will be our last resort if we don't have app locking by the end of the week.

**Comment by miyconst** [comment]
**A notice**: the app can be uninstalled only from the store which it was installed from. That means the same application in different stores is treated as two different apps, but they can't be started at the same time, because of the same name.

**Comment by andwah** [comment]
> That does not fair, what if we want to configure different persistent apps for different databases?

The application configuration file is per database.

**Comment by andwah** [comment]
As far as the Administrator and the AppStoreClient this is done.

**Comment by warpech** [comment]
Great, thanks! @miyconst will you test?

**Comment by miyconst** [comment]
@alemoi uploaded daily build with changes from @andwah `2.0.10285.2`, thanks him for that.

First, I was looking for some xml file configuration, because administrator has no GUI changes, but after further investigation I discovered that `font-awesome` is not included in the build, that is why the `lock` button which should be here:

![image](https://cloud.githubusercontent.com/assets/6435556/9258123/41a32638-4202-11e5-8600-65fe0d8e51e6.png)

 is not visible.

**Comment by miyconst** [comment]
The *Uninstall* button is visible for locked, but not started apps.

**Comment by warpech** [comment]
@andwah to fix the Font Awesome issue and trigger the build

**Comment by andwah** [comment]
Sorry, i forgot to mark the included files in the visual studio to "copy to output directory".

A new version has been generated.

**Comment by miyconst** [comment]
Tested. Works fine.
