### ISSUE TITLE
AppStoreClient does not work if Administrator is unavailable

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#12]
Currently, AppStoreClient JavaScript makes a client-server connection to Administrator port 8181. This is unsecure and not acceptable in the long term.

If Administrator is blocked behind a firewall, AppStoreClient does not work now. It should work anyway.

Long term solution: AppStoreClient should create a **server-side** (not client-side as now) connection between AppStoreClient and Administrator.

Short term solution: expose app store parts of Administrator on an additional port.

WDYT? cc @alemoi, @andwah, @miyconst

**Comment by andwah** [comment]
I changed the port number on the server side to 8182 (i exposes the needed api for the AppStoreClient), i also updated the portnumber on the client-side to 8182

**Comment by warpech** [comment]
@miyconst can you test if it works? The installer is available in the build server. 

I will expose port 8182 in playground machine.

**Comment by miyconst** [comment]
Yes, it works! I have updated the server and now all of the playgrounds work.

**Comment by warpech** [comment]
![](https://lh3.googleusercontent.com/-MFoi4YLEjzQ/VIDikQYR7LI/AAAAAAAABrw/FTdQ-jv4LtI/s160-c-no/Callouts_Internet_Yay.png)
