### ISSUE TITLE
Allow markdown in description

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#16]
Use https://github.com/Juicy/juicy-markdown to render markdown as HTML

**Comment by miyconst** [comment]
Done.

`juicy-markdown` puts content inside a `p` which adds redundant margin, to remove that margin I applied negative values to the description container `margin: -10px 5px;`.

**Comment by warpech** [comment]
Why not just set margin of `<p>` to 0?

**Comment by miyconst** [comment]
Because it will also remove margin between two `<p>`, and I don't want that.

**Comment by warpech** [comment]
:+1:
