### ISSUE TITLE
Implement poor man's categories

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#17]
Until #15 is done, we discussed implementing categories as separate app stores.

@andwah will create 2 new app stores "Essentials" and "Developer Samples"

@miyconst will make them visible by default in App Store Client

**Comment by andwah** [comment]
**Essentials** and **Developer Samples** stores created

**Comment by warpech** [comment]
Great! 

From now on, Launcher, AppStoreClient, SignIn, GoogleSignIn should be put in **Essentials** app store.

Other apps should be put in **Developer Samples**.

@miyconst can you test that?

**Comment by miyconst** [comment]
Checked.

Now AppStoreClient shows "Essentials" and "Developer Samples" stores by default.

- **Essentials** - Launcher, AppStoreClient
- **Developer Samples** - Barcodes, Images, People, Procurement, Products

The apps we are not going to demonstrate in the Playground are all in the polyjuice store.
