### ISSUE TITLE
Order the apps alphabetically

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#2]
Currently the order is from the oldest to the newest apps, which makes the App Store client hard to use.

**Comment by andwah** [comment]
The order is now based on the application display name.

**Comment by warpech** [comment]
The order seems to be wrong again. @miyconst could you take a look?

**Comment by miyconst** [comment]
I see that @andwah has made the sorting and then removed it in https://github.com/Polyjuice/AppStoreClient/commit/3d7e81f9f3aeac5834b6fc6a09bd9274b5f4bb9e with comments:
>Removed "buggy" orderBy

I think that this should be resolved on server side level, in this class:
https://github.com/Starcounter/Starcounter/blob/c331305981bc50b47eef07c86b895b0e93112de5/src/Starcounter.Administrator/Server/Managers/AppStoreManager.cs#L278

If this is wrong, and the sorting should be done on the client side, I can do that.

**Comment by alemoi** [comment]
@chrhol is it possible to sort the JSON list after its been populated? Or should the handler  "/appstore/apps" already return a sorted list? What do you think?

**Comment by andwah** [comment]
@alemoi I think that the client should sort the list.
I had a sorting filter on the client before but it turned out that it was a bit buggy and i had to remove it.  
I havent yet found a working sort filter.

**Comment by miyconst** [comment]
@warpech, @alemoi, @andwah, we should all together agree on a solution, because me and @warpech agreed to make server side sorting.

**Comment by warpech** [comment]
There are 2 problems with client-side sorting:

1) the client side should be logicless
2) sorting the array changes the array indexes

@miyconst can you think of a solution which would avoid problem #2? If so then we can accept client-side sorting as a temporary solution.

In the long term, server needs to support sorting and pagination, as well as app categories, searching, etc.

**Comment by miyconst** [comment]
2. Sure, we can add a custom web-component which would accept original list of apps, then sort it and save to an internal variable, bind the html template to the variable.

It should work, I guess.

**Comment by warpech** [comment]
Ok, please do so

**Comment by miyconst** [comment]
Done. Added a new element `app-store-client-root`. Also added app version number to the right of the name, reduced `line-height` of the description to fit long descriptions. Now it looks like this:

![app-store](https://cloud.githubusercontent.com/assets/6435556/8352434/bc854048-1b3d-11e5-81ec-71e64c9aea46.png)

**Comment by warpech** [comment]
Thanks!
