### ISSUE TITLE
"Open" button is hardcoded to localhost:8080

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#20]
"Open" button should switch to the app in the current host, but it tries to open it on localhost:8080:

<img width="1028" alt="screenshot 2015-08-14 15 19 05" src="https://cloud.githubusercontent.com/assets/566463/9274727/5c35c690-4298-11e5-847c-bb89a6b138d6.png">

**Comment by miyconst** [comment]
This was an easy task. I just removed `http://localhost:8080` from the Open button url. Now it is `/{{AppName}}`.

Should I update all of the Playgrounds with this single fix?

**Comment by miyconst** [comment]
Released and updated all Playgrounds.
