### ISSUE TITLE
Replace Skyper image

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#3]
Replace [Skyper image](https://github.com/Polyjuice/AppStoreClient/blob/master/src/AppStoreClient/wwwroot/AppStoreClient/bg/Banner_Skyper.jpg) with a zoomed-in fragment of "S" logo.

Something similar to [GoogleSignIn app image](https://github.com/Polyjuice/AppStoreClient/blob/master/src/AppStoreClient/wwwroot/AppStoreClient/bg/Banner_GoogleSignIn.jpg)

The purpose is to unfocus the Skyper app from its own branding to being just a piece of a larger picture.

**Comment by miyconst** [comment]
I am not a good designer, that is why I would really appreciate any comments. Here are five images, which one is the best? Or maybe I am looking at a wrong direction?
`#1`
![skyper-1](https://cloud.githubusercontent.com/assets/6435556/8035286/e37a06f0-0df7-11e5-8744-d150eb11bd97.png)

`#2`
![skyper-2](https://cloud.githubusercontent.com/assets/6435556/8035287/e5d41030-0df7-11e5-8472-2f5f18b779fd.png)

`#3`
![skyper-3](https://cloud.githubusercontent.com/assets/6435556/8035288/e83cc362-0df7-11e5-9fb6-9d77f79b3e2f.png)

`#4`
![skyper-4](https://cloud.githubusercontent.com/assets/6435556/8035293/eac8d724-0df7-11e5-8fba-1f2d3304e67c.png)

`#5`
![skyper-5](https://cloud.githubusercontent.com/assets/6435556/8035294/ed41bcaa-0df7-11e5-88f0-5e55dc533129.png)

**Comment by warpech** [comment]
I would take #3 or #5, whichever you like more

**Comment by miyconst** [comment]
Done, took the #3.
