### ISSUE TITLE
"newadmin" branch only works on localhost

### ISSUE THREAD

**Issue by warpech** [Polyjuice/AppStoreClient#4]
I get to my Starcounter installation from a remote machine, with a URL `http://10.211.55.4:8080/appstoreclient`

Puppet connection to Administrator is refused with the following error: 

> XMLHttpRequest cannot load http://10.211.55.4:8181/api/servermodel. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:8080' that is not equal to the supplied origin. Origin 'http://10.211.55.4:8080' is therefore not allowed access.

**Comment by andwah** [comment]
I fixed the header ```Access-Control-Allow-Origin``` on the request.
