### ISSUE TITLE
Page refresh is required after app start/stop

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/AppStoreClient#9]
After an app has been started/stopped application page refresh is required to see the changes.

Otherwise the page stacks in the previous no longer working condition.

Things to do:

- In AppStoreClient refresh page once app start/stop call back received.
- Check if application page (for example Products) keep working after some other app (for example Images) started.
- The ultimate goal is to automatically detect app start/stop events and inject/remove html parts for those apps without changing the session.

cc @warpech.

**Comment by miyconst** [comment]
Now AppStoreClient refreshes itself once an app installed or uninstalled.

**Comment by miyconst** [comment]
Starting a new app does not break existing sessions.

If I have Products app running and opened, and then start Images app, it not only won't break session, but also will inject Images part once I navigate to another product.

LaunchPad and Launcher menu require page refresh to display new applications.

**Comment by miyconst** [comment]
Stopping application kills sessions.

If I stop an app and then try to operate on an already opened page then the following error appears:

```
WebSocket connection closed. Status code: 1011. Reason: No session found.
```

**Comment by warpech** [comment]
The solution for this issue works for current browser tab. To achieve a better overall solution, let's proceed in a follow up issue: https://github.com/Starcounter/Starcounter/issues/2846
